### ISSUE TITLE
Private input

### ISSUE THREAD

**Issue by vishal16babu** [pepper-project/pequin#5]
Ben-Sasson, Eli, et al. "Succinct Non-Interactive Zero Knowledge for a von Neumann Architecture." USENIX Security. Vol. 2014. 2014.

This paper talks about F(x,w) where w is private input to F. But the current code implementation requires all the inputs to be public (shared with both prover and verifier). Is there any work around for that ?

**Comment by cnasikas** [comment]
Hi

Did you find any solution? Is `exo_compute` for that purpose or pequin doen't support it ?

Thanks in advanced

**Comment by maxhowald** [comment]
Pequin supports private inputs. The documentation has been updated a bit since this pull request was created. 

Please look at the section "Private prover input" in `GETTINGSTARTED.md`, and some further notes in `exo_compute.txt`

If you have any further questions or issues, please let us know! (You can open a new pull request, or send us email at pepper@pepper-project.org.)

**Comment by cnasikas** [comment]
Thanks a lot for your answer!
